default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  pool: 5
  host: localhost
  database: test
  username: test
  password: test1234

development:
  <<: *default
  database: rrrspec_development
  username: root

production:
  <<: *default
  host: localhost
  database: test
  username: test
  password: test1234
