# @format

name: RSpec

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.2.4

      - name: Install dependencies
        run: |
          gem install bundler -v 1.11.2
          bundle install

      - name: Run RSpec
        run: bundle exec rspec
